### ISSUE TITLE
No way to disable rolling of log files

### ISSUE THREAD

**Issue by AndrewKostousov** [vostok/logging.file#6] opened 2018-09-08 19:38 UTC
With the following configuration
```
new FileLog(() => new FileLogSettings
    {
        FileOpenMode = FileOpenMode.Rewrite,
        RollingStrategy = new RollingStrategyOptions {Type = RollingStrategyType.None},
        FilePath = Path.Combine(logsDir, $"FunctionalTests-{DateTime.Now:yyyy-MM-dd.HH-mm-ss}.log")
    });
```
obtained `FileLog` is doing rolling of log files on a per-second basis.

Also rolling is not disabled "by default" as it is specified in XML-docs.

**Comment by iloktionov** [comment] 2018-09-10 09:55
@AndrewKostousov the "rolling" to new files you are observing using this code is actually caused by changes of `FilePath` in the settings provided by the delegate passed to constructor. `FileLog` attempts to update its dynamic settings once in a second and observes different file names each time due to `DateTime.Now` call. It's treated as a configuration change (as opposed to built-in rolling) that forces `FileLog` to reopen its file.

**Comment by iloktionov** [comment] 2018-09-10 11:31
Closing this after adjusting settings descriptions to indicate that dynamic update and 1 sec. cooldown also apply to common file-related settings (name, open mode), not just to rolling strategies.

**Closed by iloktionov** 2018-09-10 11:31 UTC
Labels: bug

**Comment by AndrewKostousov** [comment] 2018-09-10 15:30
Thanks for clarification.
